import { motion } from "framer-motion";
import { ArrowLeft } from "lucide-react";
import { useNavigate } from "react-router-dom";

const fadeUp = (delay = 0) => ({
  initial: { opacity: 0, y: 20, filter: "blur(6px)" },
  animate: { opacity: 1, y: 0, filter: "blur(0px)" },
  transition: { delay, duration: 0.45, ease: [0.16, 1, 0.3, 1] },
});

const SECTIONS = [
  {
    title: "1. Acceptance of Terms",
    body: "By downloading, installing, or using the GolfMaps application ('the App'), you agree to be bound by these Terms of Use. If you do not agree to these terms, please do not use the App.",
  },
  {
    title: "2. Description of Service",
    body: "GolfMaps provides digital and printed golf course map posters. The App allows users to search for golf courses, generate custom poster artwork, save digital copies, track golf rounds, and order canvas prints for delivery.",
  },
  {
    title: "3. Subscriptions & Auto-Renewal",
    body: "Certain features require a paid subscription. Important details:\n\n- Subscriptions are billed on a recurring basis (weekly or annually)\n- Payment is charged to your Apple ID or Google Play account at confirmation of purchase\n- Subscriptions auto-renew unless cancelled at least 24 hours before the end of the current billing period\n- You can manage and cancel subscriptions in your device's Settings > Subscriptions\n- No refunds for partial billing periods\n- Prices may vary by region and are displayed before purchase",
  },
  {
    title: "4. Canvas Print Orders",
    body: "Canvas prints are physical goods processed through Stripe. Orders are final once submitted to our print partner. Shipping times are estimates only. Damaged items may be replaced at our discretion. See our shipping policy for full details.",
  },
  {
    title: "5. Free Trial",
    body: "If offered, free trials convert to paid subscriptions at the end of the trial period unless cancelled at least 24 hours before the trial ends. You will be charged the subscription price shown at sign-up.",
  },
  {
    title: "6. User Content",
    body: "You retain ownership of any personal data you provide (round scores, photos, notes). By using the App, you grant GolfMaps a non-exclusive, worldwide license to process this data solely to provide the service.",
  },
  {
    title: "7. Intellectual Property",
    body: "All poster designs, artwork, course map renderings, and visual elements generated by the App are the intellectual property of GolfMaps. Digital downloads are licensed for personal, non-commercial use only. You may not resell, redistribute, or commercially exploit generated posters.",
  },
  {
    title: "8. Acceptable Use",
    body: "You agree not to: reverse-engineer or attempt to extract the source code; use the service for any unlawful purpose; distribute malware or interfere with the service; create derivative works from our designs for commercial sale.",
  },
  {
    title: "9. Limitation of Liability",
    body: "GolfMaps provides the service 'as is' without warranties of any kind. We are not liable for any indirect, incidental, or consequential damages. Course data is sourced from OpenStreetMap and while we strive for accuracy, we cannot guarantee completeness of all course geometry.",
  },
  {
    title: "10. Termination",
    body: "We may terminate or suspend your account for violation of these terms. You may cancel your subscription at any time through your device settings. Upon termination, your right to use the App ceases immediately.",
  },
  {
    title: "11. Governing Law",
    body: "These terms are governed by the laws of the United States. Any disputes shall be resolved in the courts of [your jurisdiction].",
  },
  {
    title: "12. Changes to Terms",
    body: "We reserve the right to modify these terms at any time. Material changes will be communicated through the App. Continued use after changes constitutes acceptance of the modified terms.",
  },
  {
    title: "13. Contact",
    body: "For questions about these terms, contact us at legal@golfmaps.com.",
  },
];

const Terms = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-gradient-cream">
      <div className="px-6 pt-12 pb-10">
        <motion.div
          initial={{ opacity: 0, x: -20 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.4 }}
          className="flex items-center gap-3 mb-8"
        >
          <button onClick={() => navigate(-1)} className="w-10 h-10 rounded-full glass-card flex items-center justify-center shadow-card">
            <ArrowLeft className="w-5 h-5 text-foreground" />
          </button>
          <h1 className="font-display text-3xl font-bold text-foreground italic tracking-tight">Terms of Use</h1>
        </motion.div>

        <motion.p {...fadeUp(0.05)} className="text-xs text-muted-foreground mb-6 px-1">
          Last updated: March 2026
        </motion.p>

        <div className="space-y-5">
          {SECTIONS.map((section, i) => (
            <motion.div key={i} {...fadeUp(0.08 + i * 0.03)} className="glass-card rounded-2xl shadow-card p-5">
              <h3 className="text-sm font-semibold text-foreground mb-2">{section.title}</h3>
              <p className="text-sm text-muted-foreground leading-relaxed whitespace-pre-line">{section.body}</p>
            </motion.div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default Terms;
